services:

  api:
    build: .
    ports:
      - "5001:8081"
      - "5000:8080"
    environment:
      - RoomWroomDb__ConnectionString=Server=db;Port=5432;Database=RoomWroom;User ID=postgres;Password=postgres;
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=RoomWroom
    ports:
      - '5432:5432'